server:
  port: 8900
user:
  url: http://localhost:7090/user/
spring:
  application:
    name: consumer-order-ribbon-config
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
provide-user1: #服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #给指定的服务配置负载均衡算法